# This is your sops configuration file
# It defines which keys are used to encrypt/decrypt your secrets

keys:
  - &prohost1 age16xd88m6rdp7qy3z3e7jg69a29atx9law59uaj5ehuah9yk43dpjsfjwp2n
  - &gc7 age1787h9a9mzqq24ke5eawr98zl8es5pznpc3l4p0p3kdlu8mshrcaq4j4f0q
  - &kuroit4 age1a0yj8xjdg6s2papug34hdnvj9fer3raxvqrrqmaj029nd7nnpc4qyk4qqa
  - &hostsailor1 age1wv9fg9l37l92try4wuszkmy350g0lesk6p8dpymjyp84mcwlpavs086ew5
  - &gc5 age1kw8glmr5qcxenx39qm44n9jltn6xg7w7re0eq5ra663uxg2lp3eswegmyj
  - &gc1 age13jv42n8gsyrwr8l76azn3vw7v3532j4lq0kf0mkghk7l8vzasapq56qahs
  - &garry age13k9zm4xt9gps3j0spps2yvg3k6426d52zafefdxu8ya438w5xfzs4mz926
  - &host-c3 age1d8qydeag5df037d0r499sx6jxhpdhvpls0wqvknclzfaz6ydneysrsn83a
  - &nuyek1 age1jpatkrqnx3utff5u2lepyyvyrfw55nqu898dlumknq2453k5nuqsz3u8d3
  - &naranja1 age1xewns93yt6k47p07a7qk9yq8fs5l7pp57yydwv5p8a5ycgt3vpvss6g9fy
  - &host-c1 age187v82kjlkncr2ujkyh68p9n69xzj7sc3nt03du84ght0kx2k9umqwzdz3k
  - &gc6 age14t0war5s4qx8xtsncs02h6v4d6e9tm6mxfy7zdxt4c0rkz8qapwq6p83xf
  - &kuroit2 age1dxvx25k7ky7d4ms8v08pvwcsm20y2am84h345vyde2ulupwfjcfsxupu5r
  - &xtom1 age13d9yftrp3ya0rx5ddxmpucdsthe4632d3e2ljatxqr7md3783uyqfuya46
  - &hostdzire1 age1qnqnva8tk3axg89sfh08ysug3cwzm5serca9cvdmk5r995mk9ytq30l0as
  - &kuroit3 age1hndpvvzr29cv37k5pld5tc0qequv54nugv9kduxr8fkkrg63yugqzdmf0y
  - &onidel2 age14emudfwzc5gvqcyckm4vzm8s7yzn0jdgr52sxn5y05hqxxajuqcs5zkhsa
  - &gc2 age1eh65x2ppqe69pmec2c00na6m2v2e3hw0r9vkw4vnqzggvwjqgqqsct4z22
  - &onidel1 age1ll99rg4adepvyuaaa55gyckqp7d6jhz75e40q7xmaczu45qurppqd8yay7
  - &bakker1 age1ftk09z4wua6u2y7gy65asd5p3vgvhlvkrfvz6mtt7vrgcqdd9u3qh38hs2
  - &gc3 age1d4pfcjegp5s6fakgwajnw6pxy4la68x9cvaecdvy2eftaj92redqclrlg7
  - &virmach1 age1e2dsxlrfxcz0ynhtm5vlftz6rdahne0jvfxutc2xlqgshr77742qurzj69
  - &gc4 age1c9pkqr3qc5ue7ym3fkdrxr6wz35uw7n7rj2v0d622cpmw7aly9nq33p7vw
  - &alpha1 age1axs8juez32nfj4ee2hhc3jsv8r4hgsvcz9p3cud2zvtyt6jurafsupahxk
  - &terabit1 age1ccc92vh5jvp05zautxvu4hkw4mxkcwmjyle4p4gn8975u5a36gksgmw0q3
  - &terabit2 age1p8yr44mwsu73zwwv4nfc0sg42v0hyqmnn6repd5wxksaacd5z4vsskpfkn
  - &deluxhost1 age1v2npyaz98r74l84s5aq94sljdfmwh6u0eez258ska2se9x2t8qsspttxs6
  - &heartbeatit1 age1c5y39kzr8eqjmlydc6pnhpkesecg89yryajxahchwra3knxunvzqc49gfy
  - &kuroit1 age1gtdtc6z0dkynkufhu2qgmr2qa6svhf7q6np2v3zpr2wkl8za03es0nayxh
  # Admin users (replace with your actual keys)
  - &desk age1wgkwm0l33qxclrfkgd7fsvw0zz4lw74xsqqrrkrka83nudwrwdcqqul9mz
  - &envy age1tucpv7y4m42yv8cfztu9kpc2kg275hy3hgwc0v0h5mxhypem39csz8ucrp
  # Host keys (replace with your actual host keys)
  # You can get the age public key from your host's SSH key with:
  # `ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub`
  # for remote systems:
  # nix-shell -p ssh-to-age --run 'ssh-keyscan -p 666 1.2.3.4 | ssh-to-age'
  # Add more hosts as needed
  # - &host2 age1anotherhost

# Define creation rules for the single secrets file
creation_rules:
  - path_regex: .*\.sops\.ya?ml
    key_groups:
      - age:
          - *desk
          - *envy
          - *terabit1
          - *deluxhost1
          - *alpha1
          - *gc4
          - *virmach1
          - *terabit2
          - *bakker1
          - *onidel1
          - *heartbeatit1
          - *gc3
          - *gc2
          - *onidel2
          - *kuroit2
          - *kuroit3
          - *xtom1
          - *kuroit1
          - *hostdzire1
          - *host-c1
          - *gc6
          - *naranja1
          - *nuyek1
          - *host-c3
          - *garry
          - *gc1
          - *gc5
          - *hostsailor1
          - *kuroit4
          - *gc7
          - *prohost1
